### ISSUE TITLE
How to extract the video features from original video sequences using I3D or C3D?

### ISSUE THREAD

**Issue by FuHui-UPC** [AIM3-RUC/Youmakeup_Challenge2022#1]
How do you extract the video features from original video sequences using I3D or C3D? Could you please provide the corresponding scripts or code?

**Comment by tianchaozinv** [comment]
For C3D feature extraction, we follow https://github.com/yyuanad/Pytorch_C3D_Feature_Extractor, and for I3D feature extraction, we follow https://github.com/JaywongWang/I3D-Feature-Extractor
