### ISSUE TITLE
Why did I not reproduce the baseline scores even after 40 epoch of training?

### ISSUE THREAD

**Issue by daidaiershidi** [AIM3-RUC/Youmakeup_Challenge2022#2]
The provided model parameters (i3d_e20.model) seem to be only the results of the 20th epoch? 
But I've run 40 epoch and still haven't reproduced the baseline score.

**Comment by wdmmsyf** [comment]
To be precise, it is the best result of the first 20 epochs.
What is the score of your results? Perhaps you could check for over-fitting.

**Comment by daidaiershidi** [comment]
emmm，I did not change any of the parameters except SOLVER.BATCH_SIZE. 
New SOLVER.BATCH_SIZE is 6*4, since the limitation of storage capacity in 2080.
Up to 6 samples per GPU, and I use 4 GPU at the same time
And because the max_epoch is 40 in config (./MTVG1/configs/pool_makeup_i3d.yaml),  I've run 40 epoch. 
My best score are

```
+-------------+-------------+-------------+-------------+-------------+-------------+
| R@1,IoU@0.3 | R@1,IoU@0.5 | R@1,IoU@0.7 | R@5,IoU@0.3 | R@5,IoU@0.5 | R@5,IoU@0.7 |
+-------------+-------------+-------------+-------------+-------------+-------------+
|    44.30    |    32.52    |    16.80    |    74.52    |    60.94    |    30.60    |
+-------------+-------------+-------------+-------------+-------------+-------------+
```
in 30th epoch.
It's so sad.... 
Batchsize will reduce the number of negative samples in the contrastive learning, but just 2 less samples will make the score drop so much...

**Comment by wdmmsyf** [comment]
Sorry to hear that, but the result is now based on the selection of the appropriate hyperparameters when batchsize equals 8. You can try adjusting other hyperparameters to achieve better results. Good luck to you.

**Comment by daidaiershidi** [comment]
Thank you for your answer
